### ISSUE TITLE
Bitnami Docs are not in Sync with Github Repository

### ISSUE THREAD

**Issue by fintecheand0** [bitnami/tutorials#5]
Hello,

The documentation in the page

https://docs.bitnami.com/kubernetes/how-to/deploy-java-application-kubernetes-helm/

Is outdated.

Step 1 says:

git clone https://github.com/bitnami/tutorials
cd tutorials/java-app

But the folder cd tutorials/java-app doesn't exists.

How can it be fixed?

**Comment by juan131** [comment]
Hi @itzamnamx 

Thanks for reporting it! I created a task to review the "How to" guides about K8s. 

We will update this issue as soon as we have more news about it.

**Comment by RobinHoutevelts** [comment]
Same for https://docs.bitnami.com/kubernetes/how-to/deploy-php-application-kubernetes-helm/

There is no `php-mariadb-nginx-k8s` directory.

**Comment by carrodher** [comment]
Thank you for reporting the issue @RobinHoutevelts , I just created a task to fix it.

**Comment by raquel-campuzano** [comment]
Hi, @RobinHoutevelts,
Thank you very much for your feedback. We have updated both the repository and the documentation. Now you can follow the guide here: https://docs.bitnami.com/kubernetes/how-to/deploy-php-application-kubernetes-helm/

Don't hesitate to let us know your experience with it. Thanks!

Best Regards, 
Raquel

**Comment by RobinHoutevelts** [comment]
Thanks!

<s>guess this can be closed then</s>


nvm isn't my issue 😊

**Comment by raquel-campuzano** [comment]
You were right, @RobinHoutevelts. 
I proceed to close this issue, please feel free to re-open it if you consider it necessary.
Thanks!
